---
# Tâches pour Debian/Ubuntu - pour RedHat/CentOS, il faudrait un bloc "when"
- name: Ajouter la clé GPG du dépôt Tailscale
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Ajouter le dépôt Tailscale
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    filename: tailscale
    state: present
  when: ansible_os_family == "Debian"

- name: Installer Tailscale
  ansible.builtin.package:
    name: tailscale
    state: present
    update_cache: yes # Mettre à jour le cache après avoir ajouté le dépôt

- name: Connecter la machine au tailnet
  ansible.builtin.command: "tailscale up --authkey {{ tailscale_auth_key }} --accept-dns=false"
  args:
    creates: /var/lib/tailscale/tailscaled.state # Ne s'exécute que si non déjà configuré
  no_log: true # NE PAS AFFICHER LA CLÉ DANS LES LOGS !


      
