---
- name: Installer les paquets de base pour Python
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: Installer 'uv' (alternative rapide à pip/pip-tools)
  ansible.builtin.shell: "curl -LsSf https://astral.sh/uv/install.sh | sh"
  args:
    creates: "/home/{{ user_env_name }}/.cargo/bin/uv" # Rend la tâche idempotente
  become: true
  become_user: "{{ user_env_name }}"
  environment:
    # S'assure que l'installation se fait dans le home de l'utilisateur
    CARGO_HOME: "/home/{{ user_env_name }}/.cargo"
