---
- name: "Installer les paquets de base pour Python"
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present

- name: "Télécharger le script d'installation de 'uv'"
  ansible.builtin.get_url:
    url: "https://astral.sh/uv/install.sh"
    dest: "/home/{{ user_env_setup_name }}/install_uv.sh"
    mode: "0755"

- name: "Exécuter le script d'installation de 'uv'"
  ansible.builtin.command:
    cmd: "/home/{{ user_env_setup_name }}/install_uv.sh"
    creates: "/home/{{ user_env_setup_name }}/.cargo/bin/uv"
  become: true
  become_user: "{{ user_env_setup_name }}"
  environment:
    # S'assure que l'installation se fait dans le home de l'utilisateur
    CARGO_HOME: "/home/{{ user_env_setup_name }}/.cargo"

- name: "Ajouter l'alias python='python3' au .zshrc"
  ansible.builtin.lineinfile:
    path: "/home/{{ user_env_setup_name }}/.zshrc"
    line: "alias python='python3'"
    owner: "{{ user_env_setup_name }}"
    state: present
    insertafter: EOF
    create: true
    mode: "0644"
