---
- name: Installer Docker et Tailscale sur le VPS
  hosts: homelab
  become: true # 'become' est nécessaire pour toutes ces opérations
  vars_files:
    - vars/homelab_secrets.yml # Charger notre clé Tailscale
  vars:
    user: root
    user_home: "/home/{{ user }}"
  tasks:
#    - name: 1. Changer le hostname du serveur
#      hostname:
#        name: "{{ new_hostname }}"
#      notify: Redémarrer le serveur pour appliquer le hostname

    # --- Installation de Docker ---
    - name: 2. Installer les paquets prérequis pour Docker
      package:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - neovim
          - zsh
          - tmux
          - git
          - zsh
          - tmux
          - ripgrep
          - fzf
          - nnn
          - git
          - curl
          - unzip
          - neovim
          - fastfetcj
          - bat
          - tldr
        state: present

    # --- Installation de Tailscale ---
    - name: 3. Vérifier si Tailscale est déjà connecté
      command: tailscale ip -4
      register: tailscale_status
      changed_when: false
      failed_when: false # Ne pas échouer si la commande elle-même échoue

    - name: 3b. Installer et configurer Tailscale
      block:
        - name: Télécharger et exécuter le script d'installation Tailscale
          shell: "curl -fsSL https://tailscale.com/install.sh | sh"
          args:
            creates: /usr/bin/tailscale # Ne s'exécute que si tailscale n'est pas déjà installé

        - name: Connecter la machine au réseau Tailscale
          command: >
            tailscale up
            --authkey={{ tailscale_auth_key }}
            --accept-routes
          # L'option --ssh est géniale, elle vous permet de faire `ssh vorpax_admin@vps-zeta` depuis n'importe quelle machine de votre tailnet
          # L'option --hostname s'assure que le nom dans l'UI de Tailscale est bien celui que nous avons défini
          
      when: tailscale_status.rc != 0 # Ne s'exécute que si la machine n'est pas déjà connectée

    - name: 4. S'assurer que les services sont démarrés et activés
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - tailscaled